shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/image": ^2.0.0
  "@nuxt/kit": ^4.3.1
  "@nuxt/module-builder": ^1.0.2
  "@pinia/nuxt": ^0.11.3
  "@types/node": ^25.2.3
  "@unocss/nuxt": ^66.6.0
  "@vueuse/core": ^14.2.1
  "@vueuse/nuxt": ^14.2.1
  "@zinkawaii/eslint-config": ^0.4.2
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.4.1
  eslint: ^10.0.0
  nuxt: ^4.3.1
  pinia: ^3.0.4
  shiki: ^3.22.0
  unocss: ^66.6.0
  vue: ^3.5.28
  vue-router: ^4.6.4
  vue-tsc: ^3.2.4

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
